<?php

/**
 * REG Module
 *
 * PHP version >=5
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author     Clayton Kramer <clayton.kramer@mail.cuny.edu>
 * @package    module fms
 * @version    0.2
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */
$conf['mod_fms_name'] = _t("Facility");   // Defines the name of the module
$conf['mod_fms_menuorder'] = 60;                              // Defines this module's main menu priority
$conf['mod_fms_dependencies'] = "";
$conf['mod_fms_version'] = 1.0;
