<?php
/**
 * Client Registry Service Module
 *
 * PHP version >= 5.1
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author     Clayton Kramer <clayton.kramer@mail.cuny.edu>
 * @package    module CRS
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */

// Defines the name of the module
$conf['mod_crs_name'] = _t("Client");
// Defines this module's main menu priority
$conf['mod_crs_menuorder'] = 100;
$conf['mod_crs_dependencies'] = "fms";
$conf['mod_crs_version'] = "1.0.5";
