<?php
/**
 * Staff Registration System Module
 *
 * PHP version >= 5.1
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author     Clayton Kramer <clayton.kramer@mail.cuny.edu>
 * @package    module srs
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */

// Defines the name of the module
$conf['mod_srs_name'] = _t("Staff");
// Defines this module's main menu priority
$conf['mod_srs_menuorder'] = 1;
$conf['mod_srs_dependencies'] = "crs";
$conf['mod_srs_version'] = "1.0.5";
