<?php
/**
 * @name         Demo Instance
 * @version      1.0
 * @package      demoM
 * @author       Sneha Bhattacharya
 * @about        Developed in whole or part by the U.S. National Library of Medicine and the Sahana Foundation
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.1205
 */


$conf['mod_demoM_name']         = _t("Demo Instance");   // Defines the name of the module
$conf['mod_demoM_menuorder']    =  333;                             // Defines this module's main menu priority
$conf['mod_demoM_dependencies'] = "";
$conf['mod_demoM_version']      = 1.0;
